; ============================================================
; SOLAR MONITOR — platformio.ini
; Versi 2.0.0 — Finalisasi
; Board: ESP32 LOLIN32 Lite 4MB
; GitHub: https://github.com/britamax/esp32-solar-monitor
; ============================================================

[env:lolin32_lite]
platform = espressif32
board    = lolin32_lite
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

extra_scripts = pre:tools/compress_html.py

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.5
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
    bblanchon/ArduinoJson @ ^7.3.1
    knolleary/PubSubClient @ ^2.8
    links2004/WebSockets @ ^2.4.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DASYNC_TCP_SSL_ENABLED=0
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
    -DMQTT_MAX_PACKET_SIZE=2048
    -DMQTT_KEEPALIVE=60
    -DMQTT_SOCKET_TIMEOUT=15
    -DCONFIG_LWIP_MAX_SOCKETS=16
    -DCONFIG_LWIP_MAX_ACTIVE_TCP=16
