#!/usr/bin/env python3
# ============================================================
# compress_html.py — PlatformIO pre-build script
# ============================================================
Import("env")
import re, gzip, os

SRC_DIR = os.path.join(env["PROJECT_DIR"], "include")

HTML_FILES = [
    ("web_dashboard.h", "DASHBOARD"),
    ("web_setting.h",   "SETTING"),
    ("web_system.h",    "SYSTEM"),
    ("web_login.h",     "LOGIN"),
    ("web_log.h",       "LOGPAGE"),
]

output_lines = [
    "#pragma once",
    "// AUTO-GENERATED by compress_html.py — jangan edit manual",
    "#include <pgmspace.h>",
    "",
]

total_orig = 0
total_comp = 0

for filename, varname in HTML_FILES:
    filepath = os.path.join(SRC_DIR, filename)
    if not os.path.exists(filepath):
        print(f"[compress] SKIP {filename} (not found)")
        continue

    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    match = re.search(r'R"rawliteral\((.*?)\)rawliteral"', content, re.DOTALL)
    if not match:
        print(f"[compress] SKIP {filename} (no rawliteral found)")
        continue

    html_bytes = match.group(1).encode("utf-8")
    compressed = gzip.compress(html_bytes, compresslevel=9)

    orig_size = len(html_bytes)
    comp_size = len(compressed)
    ratio     = comp_size / orig_size * 100
    total_orig += orig_size
    total_comp += comp_size

    print(f"[compress] {filename:22}: {orig_size:6} -> {comp_size:5} bytes ({ratio:.1f}%)")

    hex_values = ", ".join(f"0x{b:02x}" for b in compressed)
    output_lines.append(f"// {filename} — {orig_size} bytes -> {comp_size} bytes ({ratio:.1f}%)")
    output_lines.append(f"const uint8_t {varname}_HTML_GZ[] PROGMEM = {{{hex_values}}};")
    output_lines.append(f"const size_t  {varname}_HTML_GZ_LEN = {comp_size};")
    output_lines.append("")

output_lines.append(f"// Total: {total_orig} bytes -> {total_comp} bytes ({total_comp/total_orig*100:.1f}%)")

out_path = os.path.join(SRC_DIR, "web_compressed.h")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines))

print(f"[compress] Output: web_compressed.h (hemat {total_orig-total_comp} bytes)")